FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat python3 make g++ curl

COPY package*.json ./
RUN npm install

COPY . .

ENV PORT=3000
ENV NODE_ENV=development

EXPOSE 3000 9229

CMD ["npm", "run", "start:dev"]
