apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: genyxo-backend-pdb
  namespace: genyxo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: genyxo-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: genyxo-frontend-pdb
  namespace: genyxo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: genyxo-frontend
