apiVersion: v1
kind: Service
metadata:
  name: {{ include "genyxo.fullname" . }}-backend-svc
  labels:
    {{- include "genyxo.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "genyxo.name" . }}-backend
