apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "genyxo.fullname" . }}-frontend
  labels:
    {{- include "genyxo.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "genyxo.name" . }}-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "genyxo.name" . }}-frontend
        app.kubernetes.io/component: frontend
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "{{ .Values.frontend.service.port }}"
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: BACKEND_URL
              value: "http://{{ include "genyxo.fullname" . }}-backend-svc:{{ .Values.backend.service.port }}"
            - name: NEXT_PUBLIC_SOCKET_URL
              value: "/"
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sleep", "3"]
