{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "genyxo.fullname" . }}-secrets
  labels:
    {{- include "genyxo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- include "genyxo.secretData" . | nindent 2 }}
{{- end }}
