apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: genyxo-staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: genyxo-staging
    app.kubernetes.io/part-of: genyxo-platform
    environment: staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: genyxo-project
  source:
    repoURL: "https://github.com/AyateAgh/WebSiteNaZakaz.git"
    targetRevision: master
    path: helm/genyxo
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
      parameters:
        - name: global.environment
          value: "staging"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: genyxo-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
